SNAT improvemets
NethServer/nethserver-firewall-base pull request #178
Opened 2021-03-16 15:38 UTC by andre8244

- While deleting a firewall object, ensure it is not used as SNAT source object
- Add inline documentation

NethServer/dev#6457

2021-03-17 13:00 UTC, edospadoni approved these changes

2021-03-17 13:00 UTC, edospadoni commented on ui/public/i18n/language.json
> +        "snat_order": "The following entries are order-sensitive. The first entry that matches a particular connection will be the one that is used"
```suggestion
        "snat_order": "The following entries are order-sensitive. The first entry that matches a particular connection will be the one that is used."
```

2021-03-18 10:10 UTC, gsanchietti requested changes

2021-03-18 10:10 UTC, gsanchietti commented on NethServer/Firewall.pm
> +
This function is built-in inside NetworksDB:
```
perldoc esmith::NetworksDB
```

2021-03-18 10:10 UTC, gsanchietti commented on NethServer/Firewall.pm
> +* interface aliases
```suggestion
* source nat rules
```

2021-03-18 10:10 UTC, gsanchietti commented on NethServer/Firewall.pm
> +    my @aliases = $self->getAliases();
```suggestion
    my @aliases = $self->{'ndb'}->aliases;
```

2021-03-18 10:10 UTC, gsanchietti commented on NethServer/Firewall.pm
> +    push(@fwrules, @aliases);
This is a bit misleading.

Please separate the logic for aliases by creating a new loop after the one `@fwrules` array.

2021-03-18 12:56 UTC, gsanchietti approved these changes

2021-03-18 12:59 UTC, merged