Ping graph for firewall
NethServer/nethserver-firewall-base pull request #202
Opened 2021-09-27 15:47 UTC by stephdl

Make a ping graph inside the dashboard of firewall

2021-09-29 14:58 UTC, gsanchietti reviewed
Thank you!

This is a great proof of concept for the work on the new Firewall dashboard!
I didn't know about `rrdtool fetch`: it's fast ans easy to parse :+1:

2021-09-29 14:58 UTC, gsanchietti commented on api/dashboard/charts
> +            $values[1] += 0;
Also the timestamp be an integer:
```suggestion
            $values[1] += 0;
            $values[0] = int($values[0]);
```

2021-09-29 15:03 UTC, edospadoni requested changes
Except a little typo, the PR looks good to me :+1:

2021-09-29 15:03 UTC, edospadoni commented on ui/src/views/Dashboard.vue
> +        ["nethserver-firewall-base//dashboard/charts"],
```suggestion
        ["nethserver-firewall-base/dashboard/charts"],
```

2021-10-01 09:25 UTC, gsanchietti commented
Replaced by #204

2021-10-01 09:25 UTC, closed without merging